### PR TITLE
Rename vignettes so they appear sorted in CRAN

### PR DESCRIPTION
**Pull request by zeehio**
Thank you for this package. It's a great introduction to PCA.

The vignettes in the CRAN page and in the pkgdown website appear to be listed in alphabetical order  according to the Rmd file names:

CRAN order:

imatge

Website order:

imatge

File names:

imatge

I believe that by renaming the .Rmd files to include a number with the order, it is possible to make them appear sorted in the CRAN docs (and possibly as well in the pkgdown website).

This pull request renames the vignettes' filenames, prefixing them from `01_` to `07_`.

Proposed file names:

imatge

Hopefully this change will help to simplify the navigation.

Thanks again!

### CODE REVIEW

**Comment by bryanhanson** [comment]
Thank you Sergio for the positive feedback and the PR.  This is a good idea. You probably noticed that I did:

```
    %\VignetteIndexEntry{LearnPCA 06: The Math Behind PCA}
```

in the vignette yaml's.  But this only sorts the titles if you do:

```
browseVignettes("LearnPCA")
```

and not in the other areas you identify.

I'm not sure if CRAN will like vignettes that start with a number, and not sure if `pkgdown` will accept that either.  Seems like they both should, but people run into weird hiccups all the time.

I'll activate the workflow checks and let's see what happens.

**Comment by bryanhanson** [comment]
Apparently file names that start with digits are not allowed.  Can you rename to "Vig_01_ .." ?
Also, in each vignette yaml you'll see:

```
    bookdown::html_document2: # use for pkgdown site
#      bookdown::pdf_document2: # use for CRAN to keep size down; breaks GHA
```

Can you comment out the html line and uncomment the pdf line?  The vignettes are huge so CRAN checks have to be run on the pdf versions.  Then, when we are ready for `pgkdown` documentation I turn it back to html versions.

And then for consistency these lines:

```
    %\VignetteIndexEntry{LearnPCA 06: The Math Behind PCA}
```

should become something like:

```
    %\VignetteIndexEntry{Vignette 06: The Math Behind PCA}
```

So each vignette gets renamed and 2 changes in its yaml.

Thank you!

Screen Shot 2022-02-24 at 9 35 29 AM

**Review by bryanhanson — COMMENTED** [review]
LGTM, thanks!  Will run checks to be sure.

**Comment by bryanhanson** [comment]
The failures are due to changes in the Github Actions workflows to build and check the package.  I have fixed and verified this on the `devel` branch.  Just merged `devel` into `master` and will now merge your PR and see where we are. I think the pkgdown workflow may also be broken but that's unrelated to anything in this PR.

**Comment by bryanhanson** [comment]
Well, that took a bit longer than it should have -- note to self: get more rest!

Everything seems to be working OK now.  Looks  like `pkgdown` uses the title from the yaml but orders things by the filename, which is what we were trying to achieve.

Thanks again Sergio!  I'll send to CRAN in a week or two (they just got the first version)>

**Comment by zeehio** [comment]
Fantastic thanks! I didn't say anything because I made the changes from my phone and I wasn't able to verify that they were working. I was waiting for my tests before replying.

I'm happy to know it has been useful. Thanks a lot for your time reviewing and merging this!

**Pull request merged**
